export enum DocumentType {
  TAX_REGISTRATION = 'TAX_REGISTRATION',
  INSURANCE = 'INSURANCE',
  TRADE_LICENSE = 'TRADE_LICENSE',
  SAFETY_CERTIFICATE = 'SAFETY_CERTIFICATE',
  AGREEMENT = 'AGREEMENT',
}
